# Site Settings
name: "Gavin Donnelly"
description: "Let's build a better Web"
url: https://habd.as
repository: https://github.com/GavinDonnelly/GavinDonnelly.github.io/

# Site Author
# See also _data/authors.yml
author:
  name: "Gavin Donnelly"
  avatar: "profile-pic.jpg"
  bio              : “Do Not Go Gentle Into That Good Night” —Dylan Thomas
  location         : "London, UK"
  github           : gavindonnelly

# Markdown
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
exclude: [vendor]
